language: python
python:
  - "3.6"
install:
  - pip install virtualenv
  - pip install coveralls
script:
  - coverage run --source= -m py.test && coverage report
after_success: coveralls
cache: pip
